# Author: Mazhar Ahmed, CTO, Oceanize Inc
# All rights reserved. Copyright (c) Oceanize Inc
version: '3'
services:
  app:
    image: oceanize/flask_app:latest
    container_name: flask_app
    restart: unless-stopped
    labels:
      project: "flask"
      day: "9 Sep 2019"
    build:
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    environment:
      # set database, memcached etc credentials
      DB_HOST: mariadb
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: slimdingo85
    volumes:
      - ./app:/app
    links:
      # network connection with these services
      - mariadb
    depends_on:
      # build those images first
      - mariadb
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "5000:5000"

  mariadb:
    container_name: flask_mysql
    # let's grab from mysql 5.7 image
    image: mariadb:latest
    volumes:
        # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    labels:
      project: "flask"
      day: "9 Sep 2019"
    # ports:
    #   - "3306:3306"
    environment:
      # credentials
      MYSQL_ROOT_PASSWORD: slimdingo85
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: slimdingo85

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local